import type { Product } from "@/types/product";

function createReviews(count: number) {
  return Array.from({ length: count }, (_, index) => ({
    rating: 5,
    comment: `Review ${index + 1}`,
    date: "2024-01-01",
    reviewerName: "Reviewer",
    reviewerEmail: "reviewer@example.com",
  }));
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    description: "Volumizing mascara for dramatic lashes.",
    category: "beauty",
    price: 9.99,
    discountPercentage: 0,
    rating: 4.94,
    stock: 50,
    thumbnail: "",
    images: [],
    reviews: createReviews(24),
  },
  {
    id: 2,
    title: "Calvin Klein CK One Eau de Toilette",
    description: "Fresh unisex fragrance with citrus notes.",
    category: "fragrances",
    price: 69.0,
    discountPercentage: 0,
    rating: 4.24,
    stock: 30,
    thumbnail: "",
    images: [],
    reviews: createReviews(51),
  },
  {
    id: 3,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple.",
    category: "smartphones",
    price: 549.0,
    discountPercentage: 12,
    rating: 4.69,
    stock: 94,
    thumbnail: "",
    images: [],
    reviews: createReviews(94),
  },
  {
    id: 4,
    title: 'MacBook Pro 14" M3',
    description: "Powerful laptop for creative professionals.",
    category: "laptops",
    price: 1999.0,
    discountPercentage: 8,
    rating: 4.82,
    stock: 20,
    thumbnail: "",
    images: [],
    reviews: createReviews(42),
  },
  {
    id: 5,
    title: "Vitamin C Brightening Serum",
    description: "Daily serum for brighter, even-toned skin.",
    category: "skincare",
    price: 24.99,
    discountPercentage: 0,
    rating: 4.71,
    stock: 80,
    thumbnail: "",
    images: [],
    reviews: createReviews(18),
  },
  {
    id: 6,
    title: "Samsung Galaxy S24 Ultra",
    description: "Flagship Android smartphone with pro camera.",
    category: "smartphones",
    price: 1199.0,
    discountPercentage: 0,
    rating: 4.88,
    stock: 35,
    thumbnail: "",
    images: [],
    reviews: createReviews(67),
  },
  {
    id: 7,
    title: "Cold-Pressed Olive Oil 1L",
    description: "Premium extra virgin olive oil.",
    category: "groceries",
    price: 14.5,
    discountPercentage: 0,
    rating: 4.55,
    stock: 120,
    thumbnail: "",
    images: [],
    reviews: createReviews(31),
  },
  {
    id: 8,
    title: "Annibale Colombo Lounge Sofa",
    description: "Comfortable lounge sofa for modern living rooms.",
    category: "furniture",
    price: 899.0,
    discountPercentage: 10,
    rating: 4.61,
    stock: 12,
    thumbnail: "",
    images: [],
    reviews: createReviews(15),
  },
];
